export const categories = [
  { id: "wallets", name: "Wallets", slug: "wallets", image: "https://placehold.co/60x60/E0BBE4/FFFFFF/png?text=Barakah+Wallets", count: 10 },
  { id: "belts", name: "Belts", slug: "belts", image: "https://placehold.co/60x60/E0BBE4/FFFFFF/png?text=Barakah+Belts", count: 10 },
  { id: "bags", name: "Bags", slug: "bags", image: "https://placehold.co/60x60/E0BBE4/FFFFFF/png?text=Barakah+Bags", count: 10 },
  { id: "accessories", name: "Accessories", slug: "accessories", image: "https://placehold.co/60x60/E0BBE4/FFFFFF/png?text=Barakah+Accessories", count: 10 },
  { id: "womens-collection", name: "Women's Collection", slug: "womens-collection", image: "https://placehold.co/60x60/E0BBE4/FFFFFF/png?text=Barakah+Women", count: 10 },
  { id: "new-arrivals", name: "New Arrivals", slug: "new-arrivals", image: "https://placehold.co/60x60/E0BBE4/FFFFFF/png?text=Barakah+New", count: 10 },
];

export const products = [
  // Wallets (10 products)
  {
    id: "1",
    name: "Barakah Classic Bifold Wallet",
    slug: "barakah-classic-bifold-wallet",
    price: 1299,
    originalPrice: 1799,
    category: "wallets",
    rating: 4.8,
    reviews: 124,
    stock: 45,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Wallet+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Wallet+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Wallet+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Wallet+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Wallet+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Wallet+Lifestyle",
    ],
    description: "Handcrafted genuine leather wallet with multiple card slots and coin pocket, featuring an embossed Barakah Hideworks logo.",
    features: ["Genuine leather", "RFID protected", "Slim profile", "Embossed BH Logo"],
  },
  {
    id: "2",
    name: "Barakah Minimalist Card Holder",
    slug: "barakah-minimalist-card-holder",
    price: 699,
    originalPrice: 999,
    category: "wallets",
    rating: 4.5,
    reviews: 201,
    stock: 60,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Card+Holder+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Card+Holder+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Card+Holder+Monogram",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Card+Holder+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Card+Holder+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Card+Holder+Lifestyle",
    ],
    description: "Slim card holder for everyday carry, adorned with a subtle BH monogram.",
    features: ["6 card slots", "Cash pocket", "Vegetable tanned leather", "BH Monogram"],
  },
  {
    id: "3",
    name: "Barakah Travel Passport Wallet",
    slug: "barakah-travel-passport-wallet",
    price: 1899,
    originalPrice: 2499,
    category: "wallets",
    rating: 4.7,
    reviews: 88,
    stock: 25,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Passport+Wallet+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Passport+Wallet+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Passport+Wallet+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Passport+Wallet+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Passport+Wallet+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Passport+Wallet+Lifestyle",
    ],
    description: "Secure passport wallet with multiple compartments for travel essentials, featuring Barakah Hideworks branding.",
    features: ["Full-grain leather", "Document slots", "Pen holder", "Barakah Branding"],
  },
  {
    id: "4",
    name: "Barakah Long Leather Wallet",
    slug: "barakah-long-leather-wallet",
    price: 1599,
    originalPrice: 2099,
    category: "wallets",
    rating: 4.6,
    reviews: 95,
    stock: 35,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Long+Wallet+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Long+Wallet+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Long+Wallet+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Long+Wallet+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Long+Wallet+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Long+Wallet+Lifestyle",
    ],
    description: "Elegant long wallet with ample space for cards and cash, showcasing premium Barakah Hideworks leather.",
    features: ["Premium leather", "Multiple card slots", "Zippered coin pocket", "Barakah Quality"],
  },
  {
    id: "5",
    name: "Barakah Coin Pouch",
    slug: "barakah-coin-pouch",
    price: 499,
    originalPrice: 699,
    category: "wallets",
    rating: 4.4,
    reviews: 150,
    stock: 70,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Coin+Pouch+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Coin+Pouch+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Coin+Pouch+Monogram",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Coin+Pouch+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Coin+Pouch+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Coin+Pouch+Lifestyle",
    ],
    description: "Compact leather coin pouch with secure closure, featuring subtle Barakah branding.",
    features: ["Soft leather", "Snap button closure", "Small and portable", "Barakah Branding"],
  },
  {
    id: "6",
    name: "Barakah RFID Blocking Wallet",
    slug: "barakah-rfid-blocking-wallet",
    price: 1499,
    originalPrice: 1999,
    category: "wallets",
    rating: 4.9,
    reviews: 110,
    stock: 40,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+RFID+Wallet+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+RFID+Wallet+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+RFID+Wallet+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+RFID+Wallet+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+RFID+Wallet+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+RFID+Wallet+Lifestyle",
    ],
    description: "Advanced RFID blocking technology for ultimate security, with Barakah Hideworks' signature design.",
    features: ["Genuine leather", "RFID protection", "Stylish design", "Barakah Signature"],
  },
  {
    id: "7",
    name: "Barakah Slim Front Pocket Wallet",
    slug: "barakah-slim-front-pocket-wallet",
    price: 899,
    originalPrice: 1199,
    category: "wallets",
    rating: 4.7,
    reviews: 130,
    stock: 50,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Slim+Wallet+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Slim+Wallet+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Slim+Wallet+Monogram",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Slim+Wallet+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Slim+Wallet+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Slim+Wallet+Lifestyle",
    ],
    description: "Ultra-slim wallet designed for front pocket carry, embodying Barakah Hideworks' minimalist aesthetic.",
    features: ["Minimalist design", "Quick access slots", "Durable", "Barakah Aesthetic"],
  },
  {
    id: "8",
    name: "Barakah Luxury Crocodile Wallet",
    slug: "barakah-luxury-crocodile-wallet",
    price: 4999,
    originalPrice: 6999,
    category: "wallets",
    rating: 4.9,
    reviews: 75,
    stock: 15,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Crocodile+Wallet+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Crocodile+Wallet+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Crocodile+Wallet+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Crocodile+Wallet+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Crocodile+Wallet+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Crocodile+Wallet+Lifestyle",
    ],
    description: "Exotic crocodile leather wallet for a touch of luxury, a true Barakah Hideworks statement piece.",
    features: ["Exotic leather", "Handcrafted", "Unique texture", "Barakah Statement"],
  },
  {
    id: "9",
    name: "Barakah Vintage Leather Wallet",
    slug: "barakah-vintage-leather-wallet",
    price: 1199,
    originalPrice: 1599,
    category: "wallets",
    rating: 4.6,
    reviews: 100,
    stock: 30,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Vintage+Wallet+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Vintage+Wallet+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Vintage+Wallet+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Vintage+Wallet+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Vintage+Wallet+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Vintage+Wallet+Lifestyle",
    ],
    description: "Distressed leather wallet with a timeless vintage look, reflecting Barakah Hideworks' heritage.",
    features: ["Distressed leather", "Classic design", "Spacious", "Barakah Heritage"],
  },
  {
    id: "10",
    name: "Barakah Zip Around Wallet",
    slug: "barakah-zip-around-wallet",
    price: 1699,
    originalPrice: 2199,
    category: "wallets",
    rating: 4.8,
    reviews: 90,
    stock: 20,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Zip+Wallet+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Zip+Wallet+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Zip+Wallet+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Zip+Wallet+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Zip+Wallet+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Zip+Wallet+Lifestyle",
    ],
    description: "Secure zip-around wallet with multiple card slots and compartments, a premium Barakah Hideworks offering.",
    features: ["Secure zipper", "Organized interior", "Premium finish", "Barakah Premium"],
  },

  // Belts (10 products)
  {
    id: "11",
    name: "Barakah Classic Black Belt",
    slug: "barakah-classic-black-belt",
    price: 899,
    originalPrice: 1199,
    category: "belts",
    rating: 4.6,
    reviews: 89,
    stock: 30,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Black+Belt+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Black+Belt+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Black+Belt+Buckle",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Black+Belt+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Black+Belt+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Black+Belt+Lifestyle",
    ],
    description: "Full-grain leather belt with brushed metal buckle, a timeless Barakah Hideworks accessory.",
    features: ["Adjustable fit", "Anti-rust buckle", "Durable stitching", "Barakah Timeless"],
  },
  {
    id: "12",
    name: "Barakah Cognac Leather Belt",
    slug: "barakah-cognac-leather-belt",
    price: 1099,
    originalPrice: 1499,
    category: "belts",
    rating: 4.8,
    reviews: 112,
    stock: 25,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Cognac+Belt+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Cognac+Belt+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Cognac+Belt+Buckle",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Cognac+Belt+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Cognac+Belt+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Cognac+Belt+Lifestyle",
    ],
    description: "Premium cognac leather belt with brass buckle, showcasing Barakah Hideworks' craftsmanship.",
    features: ["Full-grain leather", "Brass hardware", "Hand-finished", "Barakah Craftsmanship"],
  },
  {
    id: "13",
    name: "Barakah Reversible Leather Belt",
    slug: "barakah-reversible-leather-belt",
    price: 1299,
    originalPrice: 1699,
    category: "belts",
    rating: 4.7,
    reviews: 70,
    stock: 40,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Reversible+Belt+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Reversible+Belt+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Reversible+Belt+Buckle",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Reversible+Belt+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Reversible+Belt+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Reversible+Belt+Lifestyle",
    ],
    description: "Versatile reversible leather belt, black on one side, brown on the other, a Barakah Hideworks essential.",
    features: ["Two-in-one design", "Genuine leather", "Stylish buckle", "Barakah Essential"],
  },
  {
    id: "14",
    name: "Barakah Braided Leather Belt",
    slug: "barakah-braided-leather-belt",
    price: 999,
    originalPrice: 1399,
    category: "belts",
    rating: 4.5,
    reviews: 60,
    stock: 30,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Braided+Belt+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Braided+Belt+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Braided+Belt+Buckle",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Braided+Belt+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Braided+Belt+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Braided+Belt+Lifestyle",
    ],
    description: "Hand-braided leather belt for a unique look, part of the Barakah Hideworks artisanal collection.",
    features: ["Handcrafted braid", "Soft leather", "Casual style", "Barakah Artisanal"],
  },
  {
    id: "15",
    name: "Barakah Automatic Buckle Belt",
    slug: "barakah-automatic-buckle-belt",
    price: 1499,
    originalPrice: 1999,
    category: "belts",
    rating: 4.9,
    reviews: 80,
    stock: 20,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Auto+Buckle+Belt+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Auto+Buckle+Belt+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Auto+Buckle+Belt+Buckle",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Auto+Buckle+Belt+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Auto+Buckle+Belt+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Auto+Buckle+Belt+Lifestyle",
    ],
    description: "Convenient automatic buckle belt with a sleek design, a modern offering from Barakah Hideworks.",
    features: ["Ratchet system", "Easy adjustment", "High-quality leather", "Barakah Modern"],
  },
  {
    id: "16",
    name: "Barakah Distressed Leather Belt",
    slug: "barakah-distressed-leather-belt",
    price: 1199,
    originalPrice: 1599,
    category: "belts",
    rating: 4.6,
    reviews: 55,
    stock: 28,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Distressed+Belt+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Distressed+Belt+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Distressed+Belt+Buckle",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Distressed+Belt+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Distressed+Belt+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Distressed+Belt+Lifestyle",
    ],
    description: "Vintage-style distressed leather belt for a rugged look, embodying Barakah Hideworks' rustic charm.",
    features: ["Aged finish", "Durable leather", "Unique character", "Barakah Rustic"],
  },
  {
    id: "17",
    name: "Barakah Formal Dress Belt",
    slug: "barakah-formal-dress-belt",
    price: 1399,
    originalPrice: 1799,
    category: "belts",
    rating: 4.8,
    reviews: 65,
    stock: 32,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Formal+Belt+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Formal+Belt+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Formal+Belt+Buckle",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Formal+Belt+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Formal+Belt+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Formal+Belt+Lifestyle",
    ],
    description: "Elegant leather belt perfect for formal occasions, a sophisticated choice from Barakah Hideworks.",
    features: ["Smooth finish", "Polished buckle", "Sophisticated", "Barakah Sophistication"],
  },
  {
    id: "18",
    name: "Barakah Casual Leather Belt",
    slug: "barakah-casual-leather-belt",
    price: 799,
    originalPrice: 1099,
    category: "belts",
    rating: 4.5,
    reviews: 90,
    stock: 45,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Casual+Belt+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Casual+Belt+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Casual+Belt+Buckle",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Casual+Belt+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Casual+Belt+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Casual+Belt+Lifestyle",
    ],
    description: "Comfortable and stylish leather belt for everyday wear, a versatile piece from Barakah Hideworks.",
    features: ["Soft leather", "Versatile design", "Durable", "Barakah Versatile"],
  },
  {
    id: "19",
    name: "Barakah Exotic Leather Belt",
    slug: "barakah-exotic-leather-belt",
    price: 2499,
    originalPrice: 3299,
    category: "belts",
    rating: 4.9,
    reviews: 40,
    stock: 15,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Exotic+Belt+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Exotic+Belt+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Exotic+Belt+Buckle",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Exotic+Belt+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Exotic+Belt+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Exotic+Belt+Lifestyle",
    ],
    description: "Unique belt made from exotic leather, a true statement piece from Barakah Hideworks.",
    features: ["Rare leather", "Handcrafted", "Luxurious", "Barakah Unique"],
  },
  {
    id: "20",
    name: "Barakah Wide Leather Belt",
    slug: "barakah-wide-leather-belt",
    price: 1099,
    originalPrice: 1499,
    category: "belts",
    rating: 4.7,
    reviews: 50,
    stock: 25,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Wide+Belt+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Wide+Belt+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Wide+Belt+Buckle",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Wide+Belt+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Wide+Belt+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Wide+Belt+Lifestyle",
    ],
    description: "Fashionable wide leather belt for a bold look, a stylish addition from Barakah Hideworks.",
    features: ["Bold design", "High-quality leather", "Statement piece", "Barakah Stylish"],
  },

  // Bags (10 products)
  {
    id: "21",
    name: "Barakah Luxe Handbag",
    slug: "barakah-luxe-handbag",
    price: 5999,
    originalPrice: 7999,
    category: "bags",
    rating: 4.9,
    reviews: 150,
    stock: 20,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Luxe+Handbag+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Luxe+Handbag+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Luxe+Handbag+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Luxe+Handbag+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Luxe+Handbag+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Luxe+Handbag+Lifestyle",
    ],
    description: "Elegant and spacious handbag for the modern woman, featuring Barakah Hideworks' luxury design.",
    features: ["Genuine leather", "Multiple compartments", "Stylish design", "Barakah Luxury"],
  },
  {
    id: "22",
    name: "Barakah Heritage Tote",
    slug: "barakah-heritage-tote",
    price: 4499,
    originalPrice: 5999,
    category: "bags",
    rating: 4.8,
    reviews: 120,
    stock: 25,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Heritage+Tote+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Heritage+Tote+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Heritage+Tote+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Heritage+Tote+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Heritage+Tote+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Heritage+Tote+Lifestyle",
    ],
    description: "Versatile tote bag perfect for work or daily use, a classic from Barakah Hideworks.",
    features: ["Spacious interior", "Durable straps", "High-quality leather", "Barakah Classic"],
  },
  {
    id: "23",
    name: "Barakah Signature Sling Bag",
    slug: "barakah-signature-sling-bag",
    price: 2999,
    originalPrice: 3999,
    category: "bags",
    rating: 4.7,
    reviews: 90,
    stock: 30,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Signature+Sling+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Signature+Sling+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Signature+Sling+Monogram",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Signature+Sling+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Signature+Sling+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Signature+Sling+Lifestyle",
    ],
    description: "Compact and chic sling bag for on-the-go essentials, featuring Barakah Hideworks' signature design.",
    features: ["Adjustable strap", "Secure pockets", "Modern design", "Barakah Signature"],
  },
  {
    id: "24",
    name: "Barakah Executive Briefcase",
    slug: "barakah-executive-briefcase",
    price: 6999,
    originalPrice: 8999,
    category: "bags",
    rating: 4.9,
    reviews: 67,
    stock: 10,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Executive+Briefcase+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Executive+Briefcase+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Executive+Briefcase+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Executive+Briefcase+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Executive+Briefcase+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Executive+Briefcase+Lifestyle",
    ],
    description: "Professional briefcase for business executives, a symbol of Barakah Hideworks' prestige.",
    features: ["Lockable", "Laptop sleeve", "Organizer pockets", "Barakah Prestige"],
  },
  {
    id: "25",
    name: "Barakah Travel Duffle Bag",
    slug: "barakah-travel-duffle-bag",
    price: 4999,
    originalPrice: 6499,
    category: "bags",
    rating: 4.9,
    reviews: 56,
    stock: 12,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Travel+Duffle+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Travel+Duffle+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Travel+Duffle+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Travel+Duffle+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Travel+Duffle+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Travel+Duffle+Lifestyle",
    ],
    description: "Spacious duffle bag perfect for weekend trips and gym, crafted with Barakah Hideworks' durable leather.",
    features: ["Water resistant", "Multiple compartments", "Detachable strap", "Barakah Durable"],
  },
  {
    id: "26",
    name: "Barakah Vintage Messenger Bag",
    slug: "barakah-vintage-messenger-bag",
    price: 3499,
    originalPrice: 4499,
    category: "bags",
    rating: 4.7,
    reviews: 93,
    stock: 18,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Vintage+Messenger+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Vintage+Messenger+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Vintage+Messenger+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Vintage+Messenger+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Vintage+Messenger+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Vintage+Messenger+Lifestyle",
    ],
    description: "Classic messenger bag perfect for work and everyday use, a timeless piece from Barakah Hideworks.",
    features: ["Laptop compartment", "Padded shoulder strap", "Leather lining", "Barakah Timeless"],
  },
  {
    id: "27",
    name: "Barakah Leather Backpack",
    slug: "barakah-leather-backpack",
    price: 5499,
    originalPrice: 7499,
    category: "bags",
    rating: 4.8,
    reviews: 80,
    stock: 15,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Backpack+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Backpack+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Backpack+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Backpack+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Backpack+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Backpack+Lifestyle",
    ],
    description: "Stylish and functional leather backpack for daily adventures, designed by Barakah Hideworks.",
    features: ["Comfortable straps", "Spacious main compartment", "Durable", "Barakah Design"],
  },
  {
    id: "28",
    name: "Barakah Small Crossbody Bag",
    slug: "barakah-small-crossbody-bag",
    price: 2499,
    originalPrice: 3299,
    category: "bags",
    rating: 4.6,
    reviews: 70,
    stock: 28,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Crossbody+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Crossbody+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Crossbody+Monogram",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Crossbody+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Crossbody+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Crossbody+Lifestyle",
    ],
    description: "Perfect for carrying essentials with ease and style, a compact offering from Barakah Hideworks.",
    features: ["Compact size", "Adjustable strap", "Secure closure", "Barakah Compact"],
  },
  {
    id: "29",
    name: "Barakah Leather Camera Bag",
    slug: "barakah-leather-camera-bag",
    price: 3999,
    originalPrice: 5499,
    category: "bags",
    rating: 4.7,
    reviews: 45,
    stock: 10,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Camera+Bag+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Camera+Bag+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Camera+Bag+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Camera+Bag+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Camera+Bag+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Camera+Bag+Lifestyle",
    ],
    description: "Protective and stylish bag for your camera gear, crafted with Barakah Hideworks' attention to detail.",
    features: ["Padded interior", "Customizable dividers", "Water-resistant", "Barakah Detail"],
  },
  {
    id: "30",
    name: "Barakah Leather Clutch Bag",
    slug: "barakah-leather-clutch-bag",
    price: 1999,
    originalPrice: 2599,
    category: "bags",
    rating: 4.8,
    reviews: 60,
    stock: 22,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Clutch+Bag+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Clutch+Bag+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Clutch+Bag+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Clutch+Bag+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Clutch+Bag+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Clutch+Bag+Lifestyle",
    ],
    description: "Elegant clutch bag for evening events and special occasions, a sophisticated accessory from Barakah Hideworks.",
    features: ["Sophisticated design", "Detachable strap", "Interior pockets", "Barakah Sophisticated"],
  },

  // Accessories (10 products)
  {
    id: "31",
    name: "Barakah Leather Keychain Set",
    slug: "barakah-leather-keychain-set",
    price: 399,
    originalPrice: 599,
    category: "accessories",
    rating: 4.4,
    reviews: 78,
    stock: 100,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Keychain+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Keychain+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Keychain+Monogram",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Keychain+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Keychain+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Keychain+Lifestyle",
    ],
    description: "Set of 2 handcrafted leather keychains, featuring Barakah Hideworks' subtle branding.",
    features: ["Hand stitched", "Metal ring included", "Gift ready", "Barakah Branding"],
  },
  {
    id: "32",
    name: "Barakah Leather Watch Strap",
    slug: "barakah-leather-watch-strap",
    price: 599,
    originalPrice: 799,
    category: "accessories",
    rating: 4.5,
    reviews: 89,
    stock: 55,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Watch+Strap+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Watch+Strap+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Watch+Strap+Monogram",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Watch+Strap+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Watch+Strap+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Watch+Strap+Lifestyle",
    ],
    description: "Premium leather watch strap in classic brown, a stylish accessory from Barakah Hideworks.",
    features: ["Quick release pins", "Genuine leather", "Multiple sizes", "Barakah Stylish"],
  },
  {
    id: "33",
    name: "Barakah Leather Phone Case",
    slug: "barakah-leather-phone-case",
    price: 899,
    originalPrice: 1199,
    category: "accessories",
    rating: 4.7,
    reviews: 110,
    stock: 70,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Phone+Case+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Phone+Case+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Phone+Case+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Phone+Case+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Phone+Case+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Phone+Case+Lifestyle",
    ],
    description: "Protective and stylish leather phone case, featuring Barakah Hideworks' quality.",
    features: ["Full-grain leather", "Precise cutouts", "Shock absorbent", "Barakah Quality"],
  },
  {
    id: "34",
    name: "Barakah Leather Glasses Case",
    slug: "barakah-leather-glasses-case",
    price: 799,
    originalPrice: 1099,
    category: "accessories",
    rating: 4.6,
    reviews: 60,
    stock: 40,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Glasses+Case+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Glasses+Case+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Glasses+Case+Monogram",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Glasses+Case+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Glasses+Case+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Glasses+Case+Lifestyle",
    ],
    description: "Soft leather case to protect your eyeglasses or sunglasses, a refined accessory from Barakah Hideworks.",
    features: ["Soft lining", "Secure closure", "Compact design", "Barakah Refined"],
  },
  {
    id: "35",
    name: "Barakah Leather Desk Mat",
    slug: "barakah-leather-desk-mat",
    price: 1999,
    originalPrice: 2599,
    category: "accessories",
    rating: 4.8,
    reviews: 50,
    stock: 20,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Desk+Mat+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Desk+Mat+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Desk+Mat+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Desk+Mat+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Desk+Mat+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Desk+Mat+Lifestyle",
    ],
    description: "Enhance your workspace with a premium leather desk mat, a touch of Barakah Hideworks luxury.",
    features: ["Smooth surface", "Non-slip base", "Water-resistant", "Barakah Luxury"],
  },
  {
    id: "36",
    name: "Barakah Leather Coaster Set",
    slug: "barakah-leather-coaster-set",
    price: 499,
    originalPrice: 699,
    category: "accessories",
    rating: 4.5,
    reviews: 70,
    stock: 80,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Coaster+Set+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Coaster+Set+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Coaster+Set+Monogram",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Coaster+Set+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Coaster+Set+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Coaster+Set+Lifestyle",
    ],
    description: "Set of 4 elegant leather coasters for your home or office, featuring Barakah Hideworks' quality.",
    features: ["Protective", "Stylish", "Durable", "Barakah Quality"],
  },
  {
    id: "37",
    name: "Barakah Leather Cable Organizer",
    slug: "barakah-leather-cable-organizer",
    price: 349,
    originalPrice: 499,
    category: "accessories",
    rating: 4.3,
    reviews: 90,
    stock: 120,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Cable+Organizer+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Cable+Organizer+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Cable+Organizer+Monogram",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Cable+Organizer+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Cable+Organizer+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Cable+Organizer+Lifestyle",
    ],
    description: "Keep your cables tidy with this genuine leather organizer, a practical accessory from Barakah Hideworks.",
    features: ["Snap closure", "Compact", "Travel-friendly", "Barakah Practical"],
  },
  {
    id: "38",
    name: "Barakah Leather Luggage Tag",
    slug: "barakah-leather-luggage-tag",
    price: 299,
    originalPrice: 399,
    category: "accessories",
    rating: 4.2,
    reviews: 100,
    stock: 150,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Luggage+Tag+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Luggage+Tag+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Luggage+Tag+Monogram",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Luggage+Tag+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Luggage+Tag+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Luggage+Tag+Lifestyle",
    ],
    description: "Personalize your luggage with a stylish leather tag, featuring Barakah Hideworks' elegant design.",
    features: ["Durable strap", "ID window", "Premium leather", "Barakah Elegant"],
  },
  {
    id: "39",
    name: "Barakah Leather Journal Cover",
    slug: "barakah-leather-journal-cover",
    price: 1499,
    originalPrice: 1999,
    category: "accessories",
    rating: 4.8,
    reviews: 55,
    stock: 30,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Journal+Cover+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Journal+Cover+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Journal+Cover+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Journal+Cover+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Journal+Cover+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Journal+Cover+Lifestyle",
    ],
    description: "Protect your journal in a beautiful leather cover, handcrafted by Barakah Hideworks.",
    features: ["Fits A5 journals", "Pen loop", "Handcrafted", "Barakah Handcrafted"],
  },
  {
    id: "40",
    name: "Barakah Leather Mouse Pad",
    slug: "barakah-leather-mouse-pad",
    price: 899,
    originalPrice: 1199,
    category: "accessories",
    rating: 4.6,
    reviews: 65,
    stock: 40,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Mouse+Pad+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Mouse+Pad+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Mouse+Pad+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Mouse+Pad+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Mouse+Pad+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Mouse+Pad+Lifestyle",
    ],
    description: "Smooth and comfortable leather mouse pad for precision, a premium desk accessory from Barakah Hideworks.",
    features: ["Ergonomic design", "Non-slip base", "Durable", "Barakah Desk"],
  },

  // Women's Collection (10 products)
  {
    id: "41",
    name: "Barakah Women's Luxury Tote",
    slug: "barakah-womens-luxury-tote",
    price: 6499,
    originalPrice: 8499,
    category: "womens-collection",
    rating: 4.9,
    reviews: 130,
    stock: 18,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Womens+Tote+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Tote+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Tote+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Tote+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Tote+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Tote+Lifestyle",
    ],
    description: "Spacious and elegant leather tote for the sophisticated woman, a signature piece from Barakah Hideworks.",
    features: ["Premium Italian leather", "Gold-tone hardware", "Interior pockets", "Barakah Signature"],
  },
  {
    id: "42",
    name: "Barakah Women's Crossbody Bag",
    slug: "barakah-womens-crossbody-bag",
    price: 3499,
    originalPrice: 4499,
    category: "womens-collection",
    rating: 4.8,
    reviews: 110,
    stock: 25,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Womens+Crossbody+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Crossbody+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Crossbody+Monogram",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Crossbody+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Crossbody+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Crossbody+Lifestyle",
    ],
    description: "Chic and practical crossbody bag for everyday style, designed with Barakah Hideworks' elegance.",
    features: ["Adjustable strap", "Compact yet roomy", "Secure zip closure", "Barakah Elegance"],
  },
  {
    id: "43",
    name: "Barakah Women's Leather Clutch",
    slug: "barakah-womens-leather-clutch",
    price: 2499,
    originalPrice: 3299,
    category: "womens-collection",
    rating: 4.7,
    reviews: 95,
    stock: 20,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Womens+Clutch+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Clutch+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Clutch+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Clutch+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Clutch+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Clutch+Lifestyle",
    ],
    description: "Elegant leather clutch with a detachable chain strap for versatility, a perfect accessory from Barakah Hideworks.",
    features: ["Soft lambskin leather", "Detachable chain", "Internal card slots", "Barakah Versatile"],
  },
  {
    id: "44",
    name: "Barakah Women's Shoulder Bag",
    slug: "barakah-womens-shoulder-bag",
    price: 4999,
    originalPrice: 6499,
    category: "womens-collection",
    rating: 4.9,
    reviews: 105,
    stock: 22,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Womens+Shoulder+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Shoulder+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Shoulder+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Shoulder+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Shoulder+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Shoulder+Lifestyle",
    ],
    description: "Classic leather shoulder bag, perfect for any occasion, reflecting Barakah Hideworks' timeless appeal.",
    features: ["Spacious interior", "Comfortable strap", "Premium hardware", "Barakah Timeless"],
  },
  {
    id: "45",
    name: "Barakah Women's Backpack Purse",
    slug: "barakah-womens-backpack-purse",
    price: 5499,
    originalPrice: 7499,
    category: "womens-collection",
    rating: 4.8,
    reviews: 85,
    stock: 15,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+Womens+Backpack+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Backpack+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Backpack+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Backpack+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Backpack+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+Womens+Backpack+Lifestyle",
    ],
    description: "Fashionable and practical leather backpack that doubles as a purse, a versatile choice from Barakah Hideworks.",
    features: ["Convertible straps", "Multiple pockets", "Durable construction", "Barakah Versatile"],
  },
  {
    id: "46",
    name: "Barakah New Modern Briefcase",
    slug: "barakah-new-modern-briefcase",
    price: 7499,
    originalPrice: 9999,
    category: "new-arrivals",
    rating: 5.0,
    reviews: 10,
    stock: 10,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+New+Briefcase+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Briefcase+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Briefcase+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Briefcase+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Briefcase+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Briefcase+Lifestyle",
    ],
    description: "Sleek and modern leather briefcase for the contemporary professional, a new arrival from Barakah Hideworks.",
    features: ["Full-grain leather", "Laptop compartment", "Minimalist design", "Barakah New"],
  },
  {
    id: "47",
    name: "Barakah New Compact Wallet",
    slug: "barakah-new-compact-wallet",
    price: 1099,
    originalPrice: 1499,
    category: "new-arrivals",
    rating: 4.9,
    reviews: 15,
    stock: 30,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+New+Wallet+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Wallet+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Wallet+Embossed+Logo",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Wallet+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Wallet+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Wallet+Lifestyle",
    ],
    description: "Newly designed compact leather wallet with enhanced features, a fresh addition from Barakah Hideworks.",
    features: ["RFID protected", "Quick access slots", "Premium finish", "Barakah Fresh"],
  },
  {
    id: "48",
    name: "Barakah New Artisan Belt",
    slug: "barakah-new-artisan-belt",
    price: 1599,
    originalPrice: 2099,
    category: "new-arrivals",
    rating: 5.0,
    reviews: 8,
    stock: 20,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+New+Belt+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Belt+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Belt+Buckle",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Belt+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Belt+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Belt+Lifestyle",
    ],
    description: "Handcrafted artisan leather belt with unique detailing, a new masterpiece from Barakah Hideworks.",
    features: ["Hand-stitched", "Vegetable-tanned leather", "Exclusive design", "Barakah Masterpiece"],
  },
  {
    id: "49",
    name: "Barakah New Elegant Pouch",
    slug: "barakah-new-elegant-pouch",
    price: 1799,
    originalPrice: 2399,
    category: "new-arrivals",
    rating: 4.9,
    reviews: 12,
    stock: 25,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+New+Pouch+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Pouch+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Pouch+Monogram",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Pouch+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Pouch+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Pouch+Lifestyle",
    ],
    description: "Versatile and elegant leather pouch for various uses, a new and refined offering from Barakah Hideworks.",
    features: ["Soft leather", "Secure zipper", "Multi-purpose", "Barakah Refined"],
  },
  {
    id: "50",
    name: "Barakah New Premium Card Case",
    slug: "barakah-new-premium-card-case",
    price: 799,
    originalPrice: 1099,
    category: "new-arrivals",
    rating: 4.8,
    reviews: 18,
    stock: 35,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Barakah+New+Card+Case+Main",
    images: [
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Card+Case+Main",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Card+Case+Monogram",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Card+Case+Texture",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Card+Case+Packaging",
      "https://placehold.co/600x600/E0BBE4/FFFFFF/png?text=Barakah+New+Card+Case+Lifestyle",
    ],
    description: "A sleek and premium leather card case for modern needs, the latest from Barakah Hideworks.",
    features: ["Compact design", "Genuine leather", "RFID protection", "Barakah Latest"],
  },
];

export const offers = [
  { id: "1", title: "Flat 20% Off", code: "BARAKAH20", minOrder: 999, discount: 20 },
  { id: "2", title: "First Order Special", code: "WELCOME10", minOrder: 499, discount: 10 },
  { id: "3", title: "Festive Sale", code: "EID500", minOrder: 2999, discount: 500, isFlat: true },
];

export const orders = [
  {
    id: "ORD-1001",
    date: "2026-06-15",
    status: "delivered",
    total: 2198,
    items: [{ productId: "1", name: "Barakah Classic Bifold Wallet", qty: 1, price: 1299 }],
  },
  {
    id: "ORD-1002",
    date: "2026-06-18",
    status: "shipped",
    total: 899,
    items: [{ productId: "11", name: "Barakah Classic Black Belt", qty: 1, price: 899 }],
  },
];

export const reviews = [
  { id: "1", user: "Ahmed K.", rating: 5, product: "Barakah Classic Bifold Wallet", comment: "Excellent quality leather!", date: "2026-05-10" },
  { id: "2", user: "Fatima S.", rating: 4, product: "Barakah Travel Duffle Bag", comment: "Great bag, slightly heavy.", date: "2026-05-22" },
];

export const getProductById = (id) => products.find((p) => p.id === id);
export const getProductBySlug = (slug) => products.find((p) => p.slug === slug);
export const getProductsByCategory = (category) =>
  products.filter((p) => p.category === category);
