export const categories = [
  { id: "wallets", name: "Wallets", slug: "wallets", image: "👜", count: 24 },
  { id: "belts", name: "Belts", slug: "belts", image: "🪢", count: 18 },
  { id: "bags", name: "Bags", slug: "bags", image: "👜", count: 15 },
  { id: "jackets", name: "Jackets", slug: "jackets", image: "🧥", count: 12 },
  { id: "accessories", name: "Accessories", slug: "accessories", image: "⌚", count: 20 },
];

export const products = [
  {
    id: "1",
    name: "Classic Brown Leather Wallet",
    slug: "classic-brown-wallet",
    price: 1299,
    originalPrice: 1799,
    category: "wallets",
    rating: 4.8,
    reviews: 124,
    stock: 45,
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=400",
    description: "Handcrafted genuine leather wallet with multiple card slots and coin pocket.",
    features: ["Genuine leather", "RFID protected", "Slim profile"],
  },
  {
    id: "2",
    name: "Premium Black Belt",
    slug: "premium-black-belt",
    price: 899,
    originalPrice: 1199,
    category: "belts",
    rating: 4.6,
    reviews: 89,
    stock: 30,
    image: "https://images.unsplash.com/photo-1624222247344-550fb605a10a?w=400",
    description: "Full-grain leather belt with brushed metal buckle.",
    features: ["Adjustable fit", "Anti-rust buckle", "Durable stitching"],
  },
  {
    id: "3",
    name: "Travel Leather Duffle Bag",
    slug: "travel-duffle-bag",
    price: 4999,
    originalPrice: 6499,
    category: "bags",
    rating: 4.9,
    reviews: 56,
    stock: 12,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400",
    description: "Spacious duffle bag perfect for weekend trips and gym.",
    features: ["Water resistant", "Multiple compartments", "Detachable strap"],
  },
  {
    id: "4",
    name: "Heritage Leather Jacket",
    slug: "heritage-leather-jacket",
    price: 8999,
    originalPrice: 11999,
    category: "jackets",
    rating: 4.7,
    reviews: 42,
    stock: 8,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400",
    description: "Timeless biker-style jacket with premium lambskin leather.",
    features: ["Quilted lining", "YKK zippers", "Classic fit"],
  },
  {
    id: "5",
    name: "Minimal Card Holder",
    slug: "minimal-card-holder",
    price: 699,
    originalPrice: 999,
    category: "wallets",
    rating: 4.5,
    reviews: 201,
    stock: 60,
    image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400",
    description: "Slim card holder for everyday carry.",
    features: ["6 card slots", "Cash pocket", "Vegetable tanned leather"],
  },
  {
    id: "6",
    name: "Leather Keychain Set",
    slug: "leather-keychain-set",
    price: 399,
    originalPrice: 599,
    category: "accessories",
    rating: 4.4,
    reviews: 78,
    stock: 100,
    image: "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=400",
    description: "Set of 2 handcrafted leather keychains.",
    features: ["Hand stitched", "Metal ring included", "Gift ready"],
  },
  {
    id: "7",
    name: "Vintage Tan Messenger Bag",
    slug: "vintage-tan-messenger-bag",
    price: 3499,
    originalPrice: 4499,
    category: "bags",
    rating: 4.7,
    reviews: 93,
    stock: 18,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400",
    description: "Classic messenger bag perfect for work and everyday use.",
    features: ["Laptop compartment", "Padded shoulder strap", "Leather lining"],
  },
  {
    id: "8",
    name: "Cognac Leather Belt",
    slug: "cognac-leather-belt",
    price: 1099,
    originalPrice: 1499,
    category: "belts",
    rating: 4.8,
    reviews: 112,
    stock: 25,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
    description: "Premium cognac leather belt with brass buckle.",
    features: ["Full-grain leather", "Brass hardware", "Hand-finished"],
  },
  {
    id: "9",
    name: "Executive Leather Briefcase",
    slug: "executive-leather-briefcase",
    price: 6999,
    originalPrice: 8999,
    category: "bags",
    rating: 4.9,
    reviews: 67,
    stock: 10,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400",
    description: "Professional briefcase for business executives.",
    features: ["Lockable", "Laptop sleeve", "Organizer pockets"],
  },
  {
    id: "10",
    name: "Bifold Leather Wallet",
    slug: "bifold-leather-wallet",
    price: 999,
    originalPrice: 1299,
    category: "wallets",
    rating: 4.6,
    reviews: 156,
    stock: 40,
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=400",
    description: "Classic bifold design with plenty of storage.",
    features: ["8 card slots", "2 bill compartments", "ID window"],
  },
  {
    id: "11",
    name: "Distressed Leather Jacket",
    slug: "distressed-leather-jacket",
    price: 9999,
    originalPrice: 12999,
    category: "jackets",
    rating: 4.8,
    reviews: 38,
    stock: 6,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400",
    description: "Vintage-inspired distressed leather jacket.",
    features: ["Distressed finish", "Premium hardware", "Comfort fit"],
  },
  {
    id: "12",
    name: "Leather Watch Strap",
    slug: "leather-watch-strap",
    price: 599,
    originalPrice: 799,
    category: "accessories",
    rating: 4.5,
    reviews: 89,
    stock: 55,
    image: "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=400",
    description: "Premium leather watch strap in classic brown.",
    features: ["Quick release pins", "Genuine leather", "Multiple sizes"],
  },
];

export const offers = [
  { id: "1", title: "Flat 20% Off", code: "BARAKAH20", minOrder: 999, discount: 20 },
  { id: "2", title: "First Order Special", code: "WELCOME10", minOrder: 499, discount: 10 },
  { id: "3", title: "Festive Sale", code: "EID500", minOrder: 2999, discount: 500, isFlat: true },
];

export const orders = [
  {
    id: "ORD-1001",
    date: "2026-06-15",
    status: "delivered",
    total: 2198,
    items: [{ productId: "1", name: "Classic Brown Leather Wallet", qty: 1, price: 1299 }],
  },
  {
    id: "ORD-1002",
    date: "2026-06-18",
    status: "shipped",
    total: 899,
    items: [{ productId: "2", name: "Premium Black Belt", qty: 1, price: 899 }],
  },
];

export const reviews = [
  { id: "1", user: "Ahmed K.", rating: 5, product: "Classic Brown Leather Wallet", comment: "Excellent quality leather!", date: "2026-05-10" },
  { id: "2", user: "Fatima S.", rating: 4, product: "Travel Leather Duffle Bag", comment: "Great bag, slightly heavy.", date: "2026-05-22" },
];

export const getProductById = (id) => products.find((p) => p.id === id);
export const getProductBySlug = (slug) => products.find((p) => p.slug === slug);
export const getProductsByCategory = (category) =>
  products.filter((p) => p.category === category);
