export const categories = [
  { id: "wallets", name: "Wallets", slug: "wallets", image: "https://placehold.co/60x60/E0BBE4/FFFFFF/png?text=Wallets", count: 10 },
  { id: "belts", name: "Belts", slug: "belts", image: "https://placehold.co/60x60/E0BBE4/FFFFFF/png?text=Belts", count: 10 },
  { id: "bags", name: "Bags", slug: "bags", image: "https://placehold.co/60x60/E0BBE4/FFFFFF/png?text=Bags", count: 10 },
  { id: "accessories", name: "Accessories", slug: "accessories", image: "https://placehold.co/60x60/E0BBE4/FFFFFF/png?text=Accessories", count: 10 },
  { id: "womens-collection", name: "Women's Collection", slug: "womens-collection", image: "https://placehold.co/60x60/E0BBE4/FFFFFF/png?text=Women", count: 5 },
  { id: "new-arrivals", name: "New Arrivals", slug: "new-arrivals", image: "https://placehold.co/60x60/E0BBE4/FFFFFF/png?text=New", count: 5 },
];

export const products = [
  // Wallets (10 products)
  {
    id: "1",
    name: "Classic Bifold Leather Wallet",
    slug: "classic-bifold-leather-wallet",
    price: 1299,
    originalPrice: 1799,
    category: "wallets",
    rating: 4.8,
    reviews: 124,
    stock: 45,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Wallet+1",
    description: "Handcrafted genuine leather wallet with multiple card slots and coin pocket.",
    features: ["Genuine leather", "RFID protected", "Slim profile"],
  },
  {
    id: "2",
    name: "Minimalist Card Holder",
    slug: "minimalist-card-holder",
    price: 699,
    originalPrice: 999,
    category: "wallets",
    rating: 4.5,
    reviews: 201,
    stock: 60,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Wallet+2",
    description: "Slim card holder for everyday carry.",
    features: ["6 card slots", "Cash pocket", "Vegetable tanned leather"],
  },
  {
    id: "3",
    name: "Travel Passport Wallet",
    slug: "travel-passport-wallet",
    price: 1899,
    originalPrice: 2499,
    category: "wallets",
    rating: 4.7,
    reviews: 88,
    stock: 25,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Wallet+3",
    description: "Secure passport wallet with multiple compartments for travel essentials.",
    features: ["Full-grain leather", "Document slots", "Pen holder"],
  },
  {
    id: "4",
    name: "Long Leather Wallet",
    slug: "long-leather-wallet",
    price: 1599,
    originalPrice: 2099,
    category: "wallets",
    rating: 4.6,
    reviews: 95,
    stock: 35,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Wallet+4",
    description: "Elegant long wallet with ample space for cards and cash.",
    features: ["Premium leather", "Multiple card slots", "Zippered coin pocket"],
  },
  {
    id: "5",
    name: "Coin Pouch Leather",
    slug: "coin-pouch-leather",
    price: 499,
    originalPrice: 699,
    category: "wallets",
    rating: 4.4,
    reviews: 150,
    stock: 70,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Wallet+5",
    description: "Compact leather coin pouch with secure closure.",
    features: ["Soft leather", "Snap button closure", "Small and portable"],
  },
  {
    id: "6",
    name: "RFID Blocking Wallet",
    slug: "rfid-blocking-wallet",
    price: 1499,
    originalPrice: 1999,
    category: "wallets",
    rating: 4.9,
    reviews: 110,
    stock: 40,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Wallet+6",
    description: "Advanced RFID blocking technology for ultimate security.",
    features: ["Genuine leather", "RFID protection", "Stylish design"],
  },
  {
    id: "7",
    name: "Slim Front Pocket Wallet",
    slug: "slim-front-pocket-wallet",
    price: 899,
    originalPrice: 1199,
    category: "wallets",
    rating: 4.7,
    reviews: 130,
    stock: 50,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Wallet+7",
    description: "Ultra-slim wallet designed for front pocket carry.",
    features: ["Minimalist design", "Quick access slots", "Durable"],
  },
  {
    id: "8",
    name: "Luxury Crocodile Leather Wallet",
    slug: "luxury-crocodile-leather-wallet",
    price: 4999,
    originalPrice: 6999,
    category: "wallets",
    rating: 4.9,
    reviews: 75,
    stock: 15,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Wallet+8",
    description: "Exotic crocodile leather wallet for a touch of luxury.",
    features: ["Exotic leather", "Handcrafted", "Unique texture"],
  },
  {
    id: "9",
    name: "Vintage Leather Wallet",
    slug: "vintage-leather-wallet",
    price: 1199,
    originalPrice: 1599,
    category: "wallets",
    rating: 4.6,
    reviews: 100,
    stock: 30,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Wallet+9",
    description: "Distressed leather wallet with a timeless vintage look.",
    features: ["Distressed leather", "Classic design", "Spacious"],
  },
  {
    id: "10",
    name: "Zip Around Leather Wallet",
    slug: "zip-around-leather-wallet",
    price: 1699,
    originalPrice: 2199,
    category: "wallets",
    rating: 4.8,
    reviews: 90,
    stock: 20,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Wallet+10",
    description: "Secure zip-around wallet with multiple card slots and compartments.",
    features: ["Secure zipper", "Organized interior", "Premium finish"],
  },

  // Belts (10 products)
  {
    id: "11",
    name: "Classic Black Leather Belt",
    slug: "classic-black-leather-belt",
    price: 899,
    originalPrice: 1199,
    category: "belts",
    rating: 4.6,
    reviews: 89,
    stock: 30,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Belt+1",
    description: "Full-grain leather belt with brushed metal buckle.",
    features: ["Adjustable fit", "Anti-rust buckle", "Durable stitching"],
  },
  {
    id: "12",
    name: "Cognac Leather Belt",
    slug: "cognac-leather-belt",
    price: 1099,
    originalPrice: 1499,
    category: "belts",
    rating: 4.8,
    reviews: 112,
    stock: 25,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Belt+2",
    description: "Premium cognac leather belt with brass buckle.",
    features: ["Full-grain leather", "Brass hardware", "Hand-finished"],
  },
  {
    id: "13",
    name: "Reversible Leather Belt",
    slug: "reversible-leather-belt",
    price: 1299,
    originalPrice: 1699,
    category: "belts",
    rating: 4.7,
    reviews: 70,
    stock: 40,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Belt+3",
    description: "Versatile reversible leather belt, black on one side, brown on the other.",
    features: ["Two-in-one design", "Genuine leather", "Stylish buckle"],
  },
  {
    id: "14",
    name: "Braided Leather Belt",
    slug: "braided-leather-belt",
    price: 999,
    originalPrice: 1399,
    category: "belts",
    rating: 4.5,
    reviews: 60,
    stock: 30,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Belt+4",
    description: "Hand-braided leather belt for a unique look.",
    features: ["Handcrafted braid", "Soft leather", "Casual style"],
  },
  {
    id: "15",
    name: "Automatic Buckle Leather Belt",
    slug: "automatic-buckle-leather-belt",
    price: 1499,
    originalPrice: 1999,
    category: "belts",
    rating: 4.9,
    reviews: 80,
    stock: 20,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Belt+5",
    description: "Convenient automatic buckle belt with a sleek design.",
    features: ["Ratchet system", "Easy adjustment", "High-quality leather"],
  },
  {
    id: "16",
    name: "Distressed Leather Belt",
    slug: "distressed-leather-belt",
    price: 1199,
    originalPrice: 1599,
    category: "belts",
    rating: 4.6,
    reviews: 55,
    stock: 28,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Belt+6",
    description: "Vintage-style distressed leather belt for a rugged look.",
    features: ["Aged finish", "Durable leather", "Unique character"],
  },
  {
    id: "17",
    name: "Formal Dress Leather Belt",
    slug: "formal-dress-leather-belt",
    price: 1399,
    originalPrice: 1799,
    category: "belts",
    rating: 4.8,
    reviews: 65,
    stock: 32,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Belt+7",
    description: "Elegant leather belt perfect for formal occasions.",
    features: ["Smooth finish", "Polished buckle", "Sophisticated"],
  },
  {
    id: "18",
    name: "Casual Leather Belt",
    slug: "casual-leather-belt",
    price: 799,
    originalPrice: 1099,
    category: "belts",
    rating: 4.5,
    reviews: 90,
    stock: 45,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Belt+8",
    description: "Comfortable and stylish leather belt for everyday wear.",
    features: ["Soft leather", "Versatile design", "Durable"],
  },
  {
    id: "19",
    name: "Exotic Leather Belt",
    slug: "exotic-leather-belt",
    price: 2499,
    originalPrice: 3299,
    category: "belts",
    rating: 4.9,
    reviews: 40,
    stock: 15,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Belt+9",
    description: "Unique belt made from exotic leather, a true statement piece.",
    features: ["Rare leather", "Handcrafted", "Luxurious"],
  },
  {
    id: "20",
    name: "Wide Leather Belt",
    slug: "wide-leather-belt",
    price: 1099,
    originalPrice: 1499,
    category: "belts",
    rating: 4.7,
    reviews: 50,
    stock: 25,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Belt+10",
    description: "Fashionable wide leather belt for a bold look.",
    features: ["Bold design", "High-quality leather", "Statement piece"],
  },

  // Bags (10 products)
  {
    id: "21",
    name: "Luxury Women's Leather Handbag",
    slug: "luxury-womens-leather-handbag",
    price: 5999,
    originalPrice: 7999,
    category: "bags",
    rating: 4.9,
    reviews: 150,
    stock: 20,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Handbag+1",
    description: "Elegant and spacious handbag for the modern woman.",
    features: ["Genuine leather", "Multiple compartments", "Stylish design"],
  },
  {
    id: "22",
    name: "Classic Leather Tote Bag",
    slug: "classic-leather-tote-bag",
    price: 4499,
    originalPrice: 5999,
    category: "bags",
    rating: 4.8,
    reviews: 120,
    stock: 25,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Tote+Bag+1",
    description: "Versatile tote bag perfect for work or daily use.",
    features: ["Spacious interior", "Durable straps", "High-quality leather"],
  },
  {
    id: "23",
    name: "Stylish Leather Sling Bag",
    slug: "stylish-leather-sling-bag",
    price: 2999,
    originalPrice: 3999,
    category: "bags",
    rating: 4.7,
    reviews: 90,
    stock: 30,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Sling+Bag+1",
    description: "Compact and chic sling bag for on-the-go essentials.",
    features: ["Adjustable strap", "Secure pockets", "Modern design"],
  },
  {
    id: "24",
    name: "Executive Leather Briefcase",
    slug: "executive-leather-briefcase",
    price: 6999,
    originalPrice: 8999,
    category: "bags",
    rating: 4.9,
    reviews: 67,
    stock: 10,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Briefcase+1",
    description: "Professional briefcase for business executives.",
    features: ["Lockable", "Laptop sleeve", "Organizer pockets"],
  },
  {
    id: "25",
    name: "Travel Leather Duffle Bag",
    slug: "travel-leather-duffle-bag",
    price: 4999,
    originalPrice: 6499,
    category: "bags",
    rating: 4.9,
    reviews: 56,
    stock: 12,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Duffle+Bag+1",
    description: "Spacious duffle bag perfect for weekend trips and gym.",
    features: ["Water resistant", "Multiple compartments", "Detachable strap"],
  },
  {
    id: "26",
    name: "Vintage Tan Messenger Bag",
    slug: "vintage-tan-messenger-bag",
    price: 3499,
    originalPrice: 4499,
    category: "bags",
    rating: 4.7,
    reviews: 93,
    stock: 18,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Messenger+Bag+1",
    description: "Classic messenger bag perfect for work and everyday use.",
    features: ["Laptop compartment", "Padded shoulder strap", "Leather lining"],
  },
  {
    id: "27",
    name: "Leather Backpack",
    slug: "leather-backpack",
    price: 5499,
    originalPrice: 7499,
    category: "bags",
    rating: 4.8,
    reviews: 80,
    stock: 15,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Backpack+1",
    description: "Stylish and functional leather backpack for daily adventures.",
    features: ["Comfortable straps", "Spacious main compartment", "Durable"],
  },
  {
    id: "28",
    name: "Small Leather Crossbody Bag",
    slug: "small-leather-crossbody-bag",
    price: 2499,
    originalPrice: 3299,
    category: "bags",
    rating: 4.6,
    reviews: 70,
    stock: 28,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Crossbody+Bag+1",
    description: "Perfect for carrying essentials with ease and style.",
    features: ["Compact size", "Adjustable strap", "Secure closure"],
  },
  {
    id: "29",
    name: "Leather Camera Bag",
    slug: "leather-camera-bag",
    price: 3999,
    originalPrice: 5499,
    category: "bags",
    rating: 4.7,
    reviews: 45,
    stock: 10,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Camera+Bag+1",
    description: "Protective and stylish bag for your camera gear.",
    features: ["Padded interior", "Customizable dividers", "Water-resistant"],
  },
  {
    id: "30",
    name: "Leather Clutch Bag",
    slug: "leather-clutch-bag",
    price: 1999,
    originalPrice: 2599,
    category: "bags",
    rating: 4.8,
    reviews: 60,
    stock: 22,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Clutch+Bag+1",
    description: "Elegant clutch bag for evening events and special occasions.",
    features: ["Sophisticated design", "Detachable strap", "Interior pockets"],
  },

  // Accessories (10 products)
  {
    id: "31",
    name: "Leather Keychain Set",
    slug: "leather-keychain-set",
    price: 399,
    originalPrice: 599,
    category: "accessories",
    rating: 4.4,
    reviews: 78,
    stock: 100,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Keychain+1",
    description: "Set of 2 handcrafted leather keychains.",
    features: ["Hand stitched", "Metal ring included", "Gift ready"],
  },
  {
    id: "32",
    name: "Leather Watch Strap",
    slug: "leather-watch-strap",
    price: 599,
    originalPrice: 799,
    category: "accessories",
    rating: 4.5,
    reviews: 89,
    stock: 55,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Watch+Strap+1",
    description: "Premium leather watch strap in classic brown.",
    features: ["Quick release pins", "Genuine leather", "Multiple sizes"],
  },
  {
    id: "33",
    name: "Leather Phone Case",
    slug: "leather-phone-case",
    price: 899,
    originalPrice: 1199,
    category: "accessories",
    rating: 4.7,
    reviews: 110,
    stock: 70,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Phone+Case+1",
    description: "Protective and stylish leather phone case.",
    features: ["Full-grain leather", "Precise cutouts", "Shock absorbent"],
  },
  {
    id: "34",
    name: "Leather Glasses Case",
    slug: "leather-glasses-case",
    price: 799,
    originalPrice: 1099,
    category: "accessories",
    rating: 4.6,
    reviews: 60,
    stock: 40,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Glasses+Case+1",
    description: "Soft leather case to protect your eyeglasses or sunglasses.",
    features: ["Soft lining", "Secure closure", "Compact design"],
  },
  {
    id: "35",
    name: "Leather Desk Mat",
    slug: "leather-desk-mat",
    price: 1999,
    originalPrice: 2599,
    category: "accessories",
    rating: 4.8,
    reviews: 50,
    stock: 20,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Desk+Mat+1",
    description: "Enhance your workspace with a premium leather desk mat.",
    features: ["Smooth surface", "Non-slip base", "Water-resistant"],
  },
  {
    id: "36",
    name: "Leather Coaster Set",
    slug: "leather-coaster-set",
    price: 499,
    originalPrice: 699,
    category: "accessories",
    rating: 4.5,
    reviews: 70,
    stock: 80,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Coaster+Set+1",
    description: "Set of 4 elegant leather coasters for your home or office.",
    features: ["Protective", "Stylish", "Durable"],
  },
  {
    id: "37",
    name: "Leather Cable Organizer",
    slug: "leather-cable-organizer",
    price: 349,
    originalPrice: 499,
    category: "accessories",
    rating: 4.3,
    reviews: 90,
    stock: 120,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Cable+Organizer+1",
    description: "Keep your cables tidy with this genuine leather organizer.",
    features: ["Snap closure", "Compact", "Travel-friendly"],
  },
  {
    id: "38",
    name: "Leather Luggage Tag",
    slug: "leather-luggage-tag",
    price: 299,
    originalPrice: 399,
    category: "accessories",
    rating: 4.2,
    reviews: 100,
    stock: 150,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Luggage+Tag+1",
    description: "Personalize your luggage with a stylish leather tag.",
    features: ["Durable strap", "ID window", "Premium leather"],
  },
  {
    id: "39",
    name: "Leather Journal Cover",
    slug: "leather-journal-cover",
    price: 1499,
    originalPrice: 1999,
    category: "accessories",
    rating: 4.8,
    reviews: 55,
    stock: 30,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Journal+Cover+1",
    description: "Protect your journal in a beautiful leather cover.",
    features: ["Fits A5 journals", "Pen loop", "Handcrafted"],
  },
  {
    id: "40",
    name: "Leather Mouse Pad",
    slug: "leather-mouse-pad",
    price: 899,
    originalPrice: 1199,
    category: "accessories",
    rating: 4.6,
    reviews: 65,
    stock: 40,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Leather+Mouse+Pad+1",
    description: "Smooth and comfortable leather mouse pad for precision.",
    features: ["Ergonomic design", "Non-slip base", "Durable"],
  },

  // Women's Collection (5 products)
  {
    id: "41",
    name: "Women's Luxury Leather Tote",
    slug: "womens-luxury-leather-tote",
    price: 6499,
    originalPrice: 8499,
    category: "womens-collection",
    rating: 4.9,
    reviews: 130,
    stock: 18,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Womens+Tote+Bag+1",
    description: "Spacious and elegant leather tote for the sophisticated woman.",
    features: ["Premium Italian leather", "Gold-tone hardware", "Interior pockets"],
  },
  {
    id: "42",
    name: "Women's Leather Crossbody Bag",
    slug: "womens-leather-crossbody-bag",
    price: 3499,
    originalPrice: 4499,
    category: "womens-collection",
    rating: 4.8,
    reviews: 110,
    stock: 25,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Womens+Crossbody+Bag+1",
    description: "Chic and practical crossbody bag for everyday style.",
    features: ["Adjustable strap", "Compact yet roomy", "Secure zip closure"],
  },
  {
    id: "43",
    name: "Women's Leather Clutch with Chain",
    slug: "womens-leather-clutch-with-chain",
    price: 2499,
    originalPrice: 3299,
    category: "womens-collection",
    rating: 4.7,
    reviews: 95,
    stock: 20,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Womens+Clutch+Bag+1",
    description: "Elegant leather clutch with a detachable chain strap for versatility.",
    features: ["Soft lambskin leather", "Detachable chain", "Internal card slots"],
  },
  {
    id: "44",
    name: "Women's Leather Shoulder Bag",
    slug: "womens-leather-shoulder-bag",
    price: 4999,
    originalPrice: 6499,
    category: "womens-collection",
    rating: 4.9,
    reviews: 105,
    stock: 22,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Womens+Shoulder+Bag+1",
    description: "Classic leather shoulder bag, perfect for any occasion.",
    features: ["Spacious interior", "Comfortable strap", "Premium hardware"],
  },
  {
    id: "45",
    name: "Women's Leather Backpack Purse",
    slug: "womens-leather-backpack-purse",
    price: 5499,
    originalPrice: 7499,
    category: "womens-collection",
    rating: 4.8,
    reviews: 85,
    stock: 15,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=Womens+Backpack+Purse+1",
    description: "Fashionable and practical leather backpack that doubles as a purse.",
    features: ["Convertible straps", "Multiple pockets", "Durable construction"],
  },

  // New Arrivals (5 products)
  {
    id: "46",
    name: "New Arrival: Modern Leather Briefcase",
    slug: "new-modern-leather-briefcase",
    price: 7499,
    originalPrice: 9999,
    category: "new-arrivals",
    rating: 5.0,
    reviews: 10,
    stock: 10,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=New+Briefcase+1",
    description: "Sleek and modern leather briefcase for the contemporary professional.",
    features: ["Full-grain leather", "Laptop compartment", "Minimalist design"],
  },
  {
    id: "47",
    name: "New Arrival: Compact Leather Wallet",
    slug: "new-compact-leather-wallet",
    price: 1099,
    originalPrice: 1499,
    category: "new-arrivals",
    rating: 4.9,
    reviews: 15,
    stock: 30,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=New+Wallet+1",
    description: "Newly designed compact leather wallet with enhanced features.",
    features: ["RFID protected", "Quick access slots", "Premium finish"],
  },
  {
    id: "48",
    name: "New Arrival: Artisan Leather Belt",
    slug: "new-artisan-leather-belt",
    price: 1599,
    originalPrice: 2099,
    category: "new-arrivals",
    rating: 5.0,
    reviews: 8,
    stock: 20,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=New+Belt+1",
    description: "Handcrafted artisan leather belt with unique detailing.",
    features: ["Hand-stitched", "Vegetable-tanned leather", "Exclusive design"],
  },
  {
    id: "49",
    name: "New Arrival: Elegant Leather Pouch",
    slug: "new-elegant-leather-pouch",
    price: 1799,
    originalPrice: 2399,
    category: "new-arrivals",
    rating: 4.9,
    reviews: 12,
    stock: 25,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=New+Pouch+1",
    description: "Versatile and elegant leather pouch for various uses.",
    features: ["Soft leather", "Secure zipper", "Multi-purpose"],
  },
  {
    id: "50",
    name: "New Arrival: Premium Leather Card Case",
    slug: "new-premium-leather-card-case",
    price: 799,
    originalPrice: 1099,
    category: "new-arrivals",
    rating: 4.8,
    reviews: 18,
    stock: 35,
    image: "https://placehold.co/400x400/E0BBE4/FFFFFF/png?text=New+Card+Case+1",
    description: "A sleek and premium leather card case for modern needs.",
    features: ["Compact design", "Genuine leather", "RFID protection"],
  },
];

export const offers = [
  { id: "1", title: "Flat 20% Off", code: "BARAKAH20", minOrder: 999, discount: 20 },
  { id: "2", title: "First Order Special", code: "WELCOME10", minOrder: 499, discount: 10 },
  { id: "3", title: "Festive Sale", code: "EID500", minOrder: 2999, discount: 500, isFlat: true },
];

export const orders = [
  {
    id: "ORD-1001",
    date: "2026-06-15",
    status: "delivered",
    total: 2198,
    items: [{ productId: "1", name: "Classic Bifold Leather Wallet", qty: 1, price: 1299 }],
  },
  {
    id: "ORD-1002",
    date: "2026-06-18",
    status: "shipped",
    total: 899,
    items: [{ productId: "11", name: "Classic Black Leather Belt", qty: 1, price: 899 }],
  },
];

export const reviews = [
  { id: "1", user: "Ahmed K.", rating: 5, product: "Classic Bifold Leather Wallet", comment: "Excellent quality leather!", date: "2026-05-10" },
  { id: "2", user: "Fatima S.", rating: 4, product: "Travel Leather Duffle Bag", comment: "Great bag, slightly heavy.", date: "2026-05-22" },
];

export const getProductById = (id) => products.find((p) => p.id === id);
export const getProductBySlug = (slug) => products.find((p) => p.slug === slug);
export const getProductsByCategory = (category) =>
  products.filter((p) => p.category === category);
